apiVersion: "v1"
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
{{- range $key, $value := .Values.global.data }}
  {{ $key }}: {{ print $value | quote }}
{{- end }}
{{- range $key, $value := .Values.global.configMap.data }}
  {{ $key }}: {{ print $value | quote }}
{{- end }}
